- name: Add host dynamic inventory
  hosts: localhost
  gather_facts: no
  tasks:
      - name: Add host to dynamic inventory
        add_host:
          name: "proxmoxtest" # no underscore or dash
          groups: server_group
          ansible_host: "10.255.253.19"
          ansible_user: "lablink"
          ansible_password: "lablink"
          ansible_become_password: "lablink"


- name: CONFIGURE PROXMOX
  hosts: server_group
  gather_facts: no
  become: yes
  tasks:
  
      - name: wait for Debian to be ready
        wait_for_connection:
          delay: 10
          timeout: 900 # 15 minutes
        connection: local

      - name: Update host file
        copy:
          dest: /etc/hosts
          content: |
            {{ ansible_host }} {{ inventory_hostname }}.proxmox.com {{ inventory_hostname }}
            127.0.0.1 {{ inventory_hostname }}

      - name: Add Proxmox VE repository 
        shell: |
          echo "deb [arch=amd64] http://download.proxmox.com/debian/pve bookworm pve-no-subscription" > /etc/apt/sources.list.d/pve-install-repo.list
  
      - name: Add Proxmox VE repository key
        shell: |
          wget https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg -O /etc/apt/trusted.gpg.d/proxmox-release-bookworm.gpg 

      - name: Update and upgrade apt packages
        apt:
          update_cache: yes
          upgrade: dist
          cache_valid_time: 3600

      - name: Install proxmox-default-kernel
        apt:
          name: proxmox-default-kernel
          state: present

      - name: Reboot 
        reboot:
          reboot_timeout: 300

      - name: Install proxmox-ve, postfix, open-iscsi
        apt:
          name:
            - proxmox-ve
            - postfix
            - open-iscsi
          state: present


      - name: remove Debian kernel
        apt:
          name: linux-image-6.1*
          state: absent

      - name: Update grub
        shell: |
          update-grub

      - name: Remove os-prober from grub
        apt:
          name: os-prober
          state: absent


      # - name: Install gnupg package (required for adding apt keys)
      #   apt:
      #     name: gnupg
      #     state: present

      # - name: Add Proxmox VE repository key
      #   apt_key:
      #     url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
      #     state: present

      # - name: Remove enterprise repo if present
      #   file:
      #     path: /etc/apt/sources.list.d/pve-enterprise.list
      #     state: absent
      #   ignore_errors: yes

      # - name: Add Proxmox VE repository
      #   ansible.builtin.apt_repository:
      #     repo: "deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription"
      #     filename: proxmox
      #     state: present

      # - name: Update apt cache after adding repo
      #   apt:
      #     update_cache: yes

      # - name: Install proxmox-ve, postfix, open-iscsi
      #   apt:
      #     name:
      #       - proxmox-ve
      #       - postfix
      #       - open-iscsi
      #     state: present

      # - name: Disable and stop systemd-resolved service
      #   systemd:
      #     name: systemd-resolved
      #     state: stopped
      #     enabled: no
      #   ignore_errors: yes

      # - name: Ensure /etc/resolv.conf is not a symlink (optional, to avoid DNS issues)
      #   file:
      #     path: /etc/resolv.conf
      #     state: file
      #     force: yes
      #     owner: root
      #     group: root
      #     mode: '0644'

      - name: Reboot 
        reboot:
          reboot_timeout: 300
