- name: Reset switch via console
  hosts: switch
  gather_facts: False
  tasks:

    - name: print key
      debug:
        msg: "{{ ansible_key_file }}"

    - name: Run show version
      cisco.ios.ios_command:
        commands: show version
      register: output

    - name: Print output
      debug:
        var: output.stdout_lines

    # # - name: print password
    # #   debug:
    # #     msg: "{{admin_password}}"

    # - name: Send reset commands via expect over serial
    #   expect:
    #     command: "sudo screen /dev/ttyUSB0 9600"
    #     responses:
    #       ".*password for .*:": "{{ admin_password }}"
    #       # 'Username:': 'admin\n'
    #       # 'Password:': 'yourpassword\n'
    #       ">": 'enable\n'
    #       # 'Password:': 'enablepassword\n'
    #       # '#': |
    #       #   # write erase
    #       #   # reload
    #       #   # confirm
    #       "#": "show run"
    #   register: output

    # - name: print output
    #   debug:
    #     msg: "{{ output }}"
