- name: Configure VLAN on Cisco Switches
  hosts: switch
  gather_facts: no
  tasks:
    - name: Configure VLAN 100 on switch
      ios_config:
        lines:
          - vlan 100
          - name Marketing
        save_when: modified