- name: Configure VLAN on Cisco Switches
  hosts: switch
  gather_facts: no
  tasks:
    # - name: Configure VLAN 100 on switch
    #   ios_config:
    #     lines:
    #       - vlan 100
    #       - name Marketing
    #     save_when: modified

    # - name: Backup the current running config
    #   cisco.ios.ios_config:
    #     backup: yes
    #     backup_options:
          
    #       filename: "backup_config"
    #       dir_path: ./backup

    - name: Copy custom configuration file to the switch
      ansible.builtin.copy:
        src: ./template/config.jinja # Path to your local config file
        dest: flash:/configfile.cfg 

    - name: Apply the configuration from the file
      cisco.ios.ios_config:
        src: flash:/configfile.cfg  # Path on the switch where the config file was copied
        save_when: always  # Save the configuration to startup config

    - name: Reboot the switch to apply new config
      cisco.ios.ios_command:
        commands:
          - reload